module.exports={
  DB:{
    connection:'mongodb://localhost:27017/pichub-dev',
    dbname:'pichub-dev',
    port:'',
    ip:'',
    host:'',
    index:{
      unique_email:'email_unique_idx',
      unique_username:'username_unique_idx'
    }
  },
  UPLOAD_PATH_UNIX:{
    avator:"~/Workspace/FileSystem/pichub/avator/",
    thread:"~/Workspace/FileSystem/pichub/threads/"
  }
}
